### ISSUE TITLE
Use db.rnacentral in tests

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/api.rnacentral#11]
Instead of relying on hardcoded paths, check if files are there and download them if missing. Check https://github.com/ohnosequences/api.ncbitaxonomy/blob/162e0522c651a645306e1ad8bdb0891a71a7e261/src/test/scala/fileUtils.scala

**Comment by agarciamontoro** [comment]
Archived. Follow progress in [db.rnacentral](https://github.com/ohnosequences/db.rnacentral).
