### ISSUE TITLE
Update to RNACentral v9

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/api.rnacentral#12]

**Comment by eparejatobes** [comment]
Needs ohnosequences/db.rnacentral#33

**Comment by eparejatobes** [comment]
Needs #11

**Comment by eparejatobes** [comment]
db.rnacentral is already updated to v9.

**Comment by agarciamontoro** [comment]
Archived. Follow progress in [db.rnacentral](https://github.com/ohnosequences/db.rnacentral).
