### ISSUE TITLE
CSV format specification

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/api.rnacentral#6]
A csv format spec where a row represents an `Entry`.

**Comment by agarciamontoro** [comment]
What is the status of this? These issues (this one, #7 and #8) are the only ones on [Reference database milestone](https://github.com/ohnosequences/api.rnacentral/milestone/3).

I'm postponing this milestone to April 13th, so we can do it *after* Data analysis v1 milestone.

**Comment by agarciamontoro** [comment]
Archived. Follow progress in [db.rnacentral](https://github.com/ohnosequences/db.rnacentral).
