### ISSUE TITLE
From RNACentral FASTA + TSV to our CSV format

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/api.rnacentral#8]
After #6.

**Comment by agarciamontoro** [comment]
Needs #6

**Comment by agarciamontoro** [comment]
Needed-by ohnosequences/db.rna16s#80

**Comment by agarciamontoro** [comment]
Archived. Follow progress in [db.rnacentral](https://github.com/ohnosequences/db.rnacentral).
